on:
  push:
    branches:
      - main  # Set this to the branch containing your site's source code

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false  # This is necessary for JamesIves/github-pages-deploy-action

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages  # The branch the action should deploy to.
          folder: .  # The folder the action should deploy.